<?php

namespace Alnutile\Webforms\Tests;

use Illuminate\Database\Eloquent\Factory;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Tests\CreatesApplication;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app->make('Illuminate\Database\Eloquent\Factory')
            ->load(__DIR__ . '/../database/factories');


    }

    public function getFixture($file_name) {

        $file = file_get_contents(__DIR__ . '/../tests/fixtures/' . $file_name . '.json');

        return json_decode($file, true);

    }
}
